language: php
sudo: false

php:
  - 5.6
  - 7

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

script:
  # Test lint
  - find . -name \*.php -exec php -l "{}" \;

  # Install dev dependencies
  - composer require --dev phpunit/phpunit ^5.7

  # Run phpunit tests
  - make
  - cd src/Tests
  - ../../vendor/bin/phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
